---
title: "Lab: The 12 Days of Christmas"
author: "Sophie Moore, Molly Murphy, Katie Pan, Riley Sanders, Thea Yang"
date: "20 May 2021"
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
    css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Packages for Functions
library(dplyr)
library(glue)
library(stringr)
library(purrr)
library(english)
```

```{r data, include = FALSE}
xmas <- read.csv("https://www.dropbox.com/s/e584pryn8evm1gz/xmas.csv?dl=1")
```

---

## Step One:  Plurals

```{r}
# Function that takes a noun and makes it plural
# Arguments -- gift -- A string or vector of strings
# Return -- A string or vector of strings with the pluralized words

pluralize_gift <- function(gift){

gift <- case_when(
  str_detect(gift, "y$") ~ str_replace(gift, "y$", "ies"),
  str_detect(gift, "oo") ~ str_replace(gift, "oo", "ee"),
  TRUE ~ str_c(gift, "s", sep = "")
)

return(gift)

}
```


### Test Function

```{r}

pluralize_gift(xmas$Gift.Item)

purrr::map_chr(xmas$Gift.Item, pluralize_gift)

```


---


## Step Two: Creating sentences

```{r}
make_phrase <- function(num, num_word, item, verb, adjective, location) {
  
  ## Step 1: Replace NAs with blank strings
  verb <- str_replace_na(verb, "")
  adjective <- str_replace_na(adjective, "")
  location <- str_replace_na(location, "")

  
  ## Step 2: Pluralize the gift if needed
  ## Items with numbers larger than 1 should be pluralized
  ## Single items starting with a vowel should have "an" in front
  ## All other single items should have "a" in front
  
  vowel_start <- str_sub(item, 1, 1) %>% str_detect("[aeiou]")
  
  if (num > 1) {
    
    item <- pluralize_gift(item)
    
  } else if (vowel_start) {
  
      num_word <- "an"
    
  } else {
    
      num_word <- "a"
    
  }
  
  glue::glue("{num_word} {adjective} {item} {verb} {location}") %>%
    str_squish()
  
  
}
```


# Test Function

```{r}
make_phrase(num = 10,
            num_word = "ten",
            item = "lord",
            verb = "a-leaping",
            adjective = "",
            location = "")
```

```{r}
# make column with full phrases

xmas <- xmas %>%
  mutate(day.num = words(Day), 
         Full.Phrase = pmap_chr(list(num = Day, 
                                num_word = day.num, 
                                item = Gift.Item, 
                                verb = Verb, 
                                adjective = Adjective, 
                                location = Location), 
                                make_phrase)
  )

```


---


## Step Three:  Iteration.

```{r}
# Produces the string for one day of the song.
# Arguments -- dataset -- A data frame containing information about gifts
# Arguments -- line -- The number of the line for the day you want to sing about
# Arguments -- phrase_col -- The variable name for the column in the dataset that contains the gift phrases
# Return -- A string singing the line of the song with all gifts for the given day.

sing_line <- function(dataset, line, phrase_col){
  
  # Step 1: Setup the intro line
  
  num_word <- ordinal(line)
  
  intro <- glue::glue("On the {num_word} day of Christmas,")
  
  # Step 2: Sing the gift phrases

    phrases <- dataset %>% 
      pull({{phrase_col}})

   phrases[2] <- str_c(phrases[2], "and", sep = " ")
   body <- str_c(phrases[line:1], collapse = "\n")
    
  ## put it together
    
  glue::glue("{intro} my true love sent to me, \n {body}")


}

```


## Test function
```{r}
sing_line(xmas, 
          line = 2, 
          phrase_col = Full.Phrase)

```

---

## Step Four: Use Your Functions!

```{r}
xmas2 <- xmas %>%
  mutate(
    day.num = as.character(english::english(Day)), 
    Full.Phrase = pmap_chr(list(num = Day, 
                                num_word = day.num, 
                                item = Gift.Item, 
                                verb = Verb, 
                                adjective = Adjective, 
                                location = Location), 
                           make_phrase)
  )

map_chr(1:12, ~sing_line(xmas2, .x, Full.Phrase)) %>%
  str_c(collapse = "\n") %>%
  cat()

```
